DROP TABLE ALARM PURGE; 

/* 알림 */
CREATE TABLE ALARM (
	MEMBER_NO NUMBER NOT NULL, /* 알림 대상 */
	ALARM_CONTENT VARCHAR2(100) NOT NULL, /* 알림 내용 */
	ALARM_DATE DATE NOT NULL, /* 알림 날짜 */
	ALARM_CHECKED VARCHAR2(2) NOT NULL, /* 알림 확인 여부 */
	ALARM_GUBUN VARCHAR2(50) NOT NULL, /* 알림 구분(쪽지:MESSAGE, 스터디관련:STUDY, 프로젝트관련:PROJECT,  결제관련:PAY, 문의답변:ASK) */
	ALARM_DETAIL_NO NUMBER NOT NULL /* 알림 상세 번호 */
);

SELECT COUNT(ALARM_CHECKED) FROM ALARM WHERE MEMBER_NO = 28 AND ALARM_CHECKED = 'N'

ALTER TABLE ALARM
	ADD
		CONSTRAINT FK_MEMBER_TO_ALARM
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		) ON DELETE CASCADE;
		
SELECT * FROM ALARM;

SELECT MAX(MESSAGE_NO)
FROM MESSAGE
WHERE MESSAGE_SENDER_NO = 28

SELECT MAX(MESSAGE_NO) as MESSAGE_NO,MEMBER_NAME
	FROM MESSAGE INNER JOIN MEMBER ON MESSAGE_SENDER_NO=MEMBER_NO
	WHERE MESSAGE_SENDER_NO = 28 GROUP BY MEMBER_NAME

select * from alarm

--TEST DB
--쪽지
INSERT INTO ALARM VALUES(32, '정연 : 정연 쪽지 테스트', SYSDATE, 'Y', 'MESSAGE', 1);
INSERT INTO ALARM VALUES(32, '정연 : 정연 쪽지 테스트', SYSDATE, 'N', 'MESSAGE', 2);
INSERT INTO ALARM VALUES(32, '사나 : 사나 쪽지 테스트', SYSDATE, 'N', 'MESSAGE', 3);
INSERT INTO ALARM VALUES(32, '사나 : 사나 쪽지 테스트', SYSDATE, 'Y', 'MESSAGE', 4);
INSERT INTO ALARM VALUES(32, '하연수 : 하연수 쪽지 테스트', SYSDATE, 'N', 'MESSAGE', 5);
INSERT INTO ALARM VALUES(32, '한효주 : 한효주 쪽지 테스트', SYSDATE, 'N', 'MESSAGE', 6);

--스프
INSERT INTO ALARM VALUES(32, '스터디 알림 테스트1', SYSDATE, 'N', 'STUDY', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트1', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '프로젝트  알림 테스트2', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '스터디 알림 테스트2', SYSDATE, 'Y', 'STUDY', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트3', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '스터디 알림 테스트3', SYSDATE, 'N', 'STUDY', 6);
INSERT INTO ALARM VALUES(32, '스터디 알림 테스트4', SYSDATE, 'Y', 'STUDY', 6);
INSERT INTO ALARM VALUES(32, '스터디 알림 테스트5', SYSDATE, 'N', 'STUDY', 6);
INSERT INTO ALARM VALUES(32, '스터디 알림 테스트6', SYSDATE, 'N', 'STUDY', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트4', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트5', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트6', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트7', SYSDATE, 'N', 'PROJECT', 6);
INSERT INTO ALARM VALUES(32, '프로젝트 알림 테스트8', SYSDATE, 'N', 'PROJECT', 6);


--회원 관련
INSERT INTO ALARM VALUES(32, '결제 알림 테스트1', SYSDATE, 'Y', 'PAY', 1);
INSERT INTO ALARM VALUES(32, '결제 알림 테스트2', SYSDATE, 'N', 'PAY', 2);
INSERT INTO ALARM VALUES(32, '문의 알림 테스트1', SYSDATE, 'N', 'ASK', 2);




--최신순으로 가져온다
SELECT ALARM_CONTENT, ALARM_DATE, ALARM_CHECKED, ALARM_DETAIL_NO 
  FROM	(SELECT ALARM_CONTENT, ALARM_DATE, ALARM_CHECKED, ALARM_DETAIL_NO
		   FROM ALARM
		  WHERE MEMBER_NO = 32
		    AND ALARM_GUBUN = 'MESSAGE'
		  ORDER BY ALARM_DATE DESC)
 WHERE ROWNUM <= 10