/* 찜 목록 */
DROP TABLE JJIM PURGE;

/* 찜 목록 */
CREATE TABLE JJIM (
	SOUP_NO NUMBER NOT NULL, /* 스터디 / 프로젝트 번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	JJIM_DATE DATE NOT NULL /* 찜한 날짜 */
);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_SOUP_TO_JJIM
		FOREIGN KEY (
			SOUP_NO
		)
		REFERENCES SOUP (
			SOUP_NO
		) ON DELETE CASCADE;

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_MEMBER_TO_JJIM
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		) ON DELETE CASCADE;
		
SELECT * FROM JJIM


SELECT SOUP_NO, SOUP_TITLE, SOUP_FIELD1, SOUP_FIELD2, SOUP_ADDR1, SOUP_ADDR2
FROM JJIM INNER JOIN SOUP
USING (SOUP_NO)
WHERE MEMBER_NO = 31
AND SOUP_STATUS = 'RECRUIT'
ORDER BY JJIM_DATE DESC



SELECT MEMBER_NAME, MEMBER_FACE, REVIEW_SCORE, REVIEW_CONTENT, REVIEW_DATE
  FROM (SELECT MEMBER_NO, REVIEW_SCORE, REVIEW_CONTENT, REVIEW_DATE
          FROM REVIEW
         WHERE TEACHER_NO = 
                ( SELECT TEACHER_NO
                   FROM TEACHER
                   JOIN (
                         SELECT MEMBER_NO
                           FROM SOUP_MEMBER
                          WHERE SOUP_NO = 338
                            AND SOUP_MEMBER_GUBUN = 'L')
                   USING (MEMBER_NO))
                   )
  JOIN MEMBER
 USING (MEMBER_NO)
 ORDER BY REVIEW_DATE DESC





