/* 프로젝트 게시물 */
DROP SEQUENCE PROJECT_BOARD_SEQ;
DROP TABLE PROJECT_BOARD PURGE 

CREATE SEQUENCE PROJECT_BOARD_SEQ;
CREATE TABLE PROJECT_BOARD (
	PROJECT_BOARD_NO NUMBER NOT NULL, /* 게시물 번호 */
	SOUP_NO NUMBER NOT NULL, /* 프로젝트 번호 */
	MEMBER_NO NUMBER NOT NULL, /* 회원 번호 */
	PROJECT_BOARD_TITLE VARCHAR2(100) NOT NULL, /* 게시물 제목 */
	PROJECT_BOARD_CONTENT VARCHAR2(1000) NOT NULL, /* 게시물 내용 */
	PROJECT_BOARD_DATE DATE NOT NULL, /* 작성일 */
	PROJECT_BOARD_GUBUN VARCHAR2(2) NOT NULL, /* 게시물 구분 (공지사항:N, 참고/공유:R, 할일:T, 진행중:P, 완료:D)*/
	PROJECT_BOARD_ORDER NUMBER, /* 게시물 순번 */
	PROJECT_BOARD_SCOPE VARCHAR2(2) NOT NULL, /* 수정 / 삭제 권한 범위 (전체(A) , 본인만(P)) */
	PROJECT_BOARD_FIXED VARCHAR2(2) NOT NULL, /*고정 여부 YN */
	PROJECT_BOARD_START_DATE DATE, /* 일정 시작 날짜 */
	PROJECT_BOARD_END_DATE DATE, /* 일정 종료 날짜 */
	PROJECT_BOARD_FILE_URL VARCHAR2(300), /* 첨부 파일 경로 */
	PROJECT_BOARD_FILE_NAME VARCHAR2(200), /* 실제 파일 명 */
	PROJECT_BOARD_CHECKLIST_NAME VARCHAR2(50) /* 체크리스트 명 */
);

ALTER TABLE PROJECT_BOARD
	ADD
		CONSTRAINT PK_PROJECT_BOARD
		PRIMARY KEY (
			PROJECT_BOARD_NO
		);

ALTER TABLE PROJECT_BOARD
	ADD
		CONSTRAINT UK_PROJECT_BOARD
		UNIQUE (
			PROJECT_BOARD_FILE_URL
		);

ALTER TABLE PROJECT_BOARD
	ADD
		CONSTRAINT FK_SOUP_TO_PROJECT_BOARD
		FOREIGN KEY (
			SOUP_NO
		)
		REFERENCES SOUP (
			SOUP_NO
		);

ALTER TABLE PROJECT_BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_PROJECT_BOARD
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);
		

/* 체크리스트 목록 */
DROP TABLE PROJECT_CHECKLIST PURGE;

/* 체크리스트 목록 */
CREATE TABLE PROJECT_CHECKLIST (
	PROJECT_BOARD_NO NUMBER NOT NULL, /* 게시물 번호 */
	PROJECT_CHECKLIST_CONTENT VARCHAR2(50) NOT NULL, /* 목록 내용 */
	PROJECT_CHECKLIST_CHECKED VARCHAR2(2) NOT NULL, /* 체크 Y/N */
	PROJECT_CHECKLIST_DATE DATE NOT NULL /* 목록 내용 생성일 */
);

ALTER TABLE PROJECT_CHECKLIST
	ADD
		CONSTRAINT FK_PRJ_BOARD_TO_PRJ_CHECKLIST
		FOREIGN KEY (
			PROJECT_BOARD_NO
		)
		REFERENCES PROJECT_BOARD (
			PROJECT_BOARD_NO
		) ON DELETE CASCADE;

--TEST DATA
INSERT INTO PROJECT_CHECKLIST VALUES(7, '1번 체크리스트', 'N', SYSDATE);
INSERT INTO PROJECT_CHECKLIST VALUES(7, '2번 체크리스트', 'Y', SYSDATE);
INSERT INTO PROJECT_CHECKLIST VALUES(7, '3번 체크리스트', 'Y', SYSDATE);
INSERT INTO PROJECT_CHECKLIST VALUES(7, '4번 체크리스트', 'N', SYSDATE);
INSERT INTO PROJECT_CHECKLIST VALUES(7, '5번 체크리스트', 'Y', SYSDATE);

--해당 프로젝트의 게시물 가져오기(MOVABLE)
SELECT PROJECT_BOARD_NO, PROJECT_BOARD_ORDER, MEMBER_NAME, PROJECT_BOARD_TITLE,
       PROJECT_BOARD_CONTENT, PROJECT_BOARD_START_DATE, PROJECT_BOARD_END_DATE, 
       PROJECT_BOARD_FILE_NAME, PROJECT_BOARD_FILE_URL, PROJECT_BOARD_CHECKLIST_NAME
  FROM PROJECT_BOARD
 INNER JOIN MEMBER
 USING (MEMBER_NO)
 WHERE SOUP_NO = #{soupNo}
       AND PROJECT_BOARD_GUBUN = #{gubun}
 ORDER BY PROJECT_BOARD_ORDER ASC

--해당 프로젝트의 게시물 가져오기(UNMOVABLE)
SELECT PROJECT_BOARD_NO, PROJECT_BOARD_ORDER, MEMBER_NAME, PROJECT_BOARD_TITLE,
       PROJECT_BOARD_CONTENT, PROJECT_BOARD_START_DATE, PROJECT_BOARD_END_DATE, 
       PROJECT_BOARD_FILE_NAME, PROJECT_BOARD_FILE_URL, PROJECT_BOARD_CHECKLIST_NAME
  FROM PROJECT_BOARD
 INNER JOIN MEMBER
 USING(MEMBER_NO)
 WHERE SOUP_NO = #{soupNo}
       AND PROJECT_BOARD_GUBUN = #{gubun}
 ORDER BY PROJECT_BOARD_DATE ASC

