/* 강사 평가 */
DROP TABLE REVIEW PURGE; 

/* 강사 평가 */
CREATE TABLE REVIEW (
	MEMBER_NO NUMBER, /* 회원 번호 */
	SOUP_NO NUMBER, /* 스터디 / 프로젝트 번호 */
	TEACHER_NO NUMBER, /* 강사 번호 */
	REVIEW_SCORE NUMBER, /* 평점 */
	REVIEW_CONTENT VARCHAR2(4000), /* 내용 */
	REVIEW_DATE DATE /* 작성 날짜 */
);


ALTER TABLE REVIEW
	ADD
		CONSTRAINT UK_REVIEW
		UNIQUE (
			MEMBER_NO,
			SOUP_NO
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_REVIEW
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		) ON DELETE CASCADE;

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_TEACHER_TO_REVIEW
		FOREIGN KEY (
			TEACHER_NO
		)
		REFERENCES TEACHER (
			TEACHER_NO
		) ON DELETE CASCADE;

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_SOUP_TO_REVIEW
		FOREIGN KEY (
			SOUP_NO
		)
		REFERENCES SOUP (
			SOUP_NO
		) ON DELETE CASCADE;
