/* 스터디 / 프로젝트 지원 */
DROP TABLE SOUP_APPLY PURGE;

CREATE TABLE SOUP_APPLY (
	SOUP_NO NUMBER NOT NULL, /* 스터디 / 프로젝트 번호 */
	MEMBER_NO NUMBER, /* 회원 번호 */
	SOUP_APPLY_INTRO VARCHAR2(1000), /* 자기 소개 */
	SOUP_APPLY_ENTERED VARCHAR2(2), /* 승낙 여부 (승낙:Y, 대기:N, 거부:R) */
	SOUP_APPLY_DATE DATE /* 지원 날짜 */
);

ALTER TABLE SOUP_APPLY
	ADD
		CONSTRAINT FK_MEMBER_TO_SOUP_APPLY
		FOREIGN KEY (
			MEMBER_NO
		)
		REFERENCES MEMBER (
			MEMBER_NO
		);

ALTER TABLE SOUP_APPLY
	ADD
		CONSTRAINT FK_SOUP_TO_SOUP_APPLY
		FOREIGN KEY (
			SOUP_NO
		)
		REFERENCES SOUP (
			SOUP_NO
		);		
		

--테스트 데이터 생성
INSERT INTO SOUP_APPLY VALUES(21, 15, '잘부탁드립니다1', 'N', SYSDATE);
INSERT INTO SOUP_APPLY VALUES(21, 17, '잘부탁드립니다2', 'N', SYSDATE);
INSERT INTO SOUP_APPLY VALUES(21, 13, '잘부탁드립니다3', 'N', SYSDATE);
INSERT INTO SOUP_APPLY VALUES(21, 14, '잘부탁드립니다4', 'N', SYSDATE);
INSERT INTO SOUP_APPLY VALUES(21, 18, '잘부탁드립니다5', 'N', SYSDATE);

--해당 프로젝트의 신청인원 불러오기
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NAME, MEMBER_FACE
  FROM SOUP_APPLY
 INNER JOIN MEMBER
 USING (MEMBER_NO)
 WHERE SOUP_NO = 21
 		AND MEMBER_ENA = 'Y'
 		AND SOUP_APPLY_ENTERED = 'N'
 ORDER BY SOUP_APPLY_DATE ASC;

DROPYN = 'N'

--해당 프로젝트의 현재 인원과 max 인원을 가져온다.
SELECT COUNT(MEMBER_NO), SOUP_MEMBER_MAX
  FROM SOUP_MEMBER
 INNER JOIN SOUP
 USING (SOUP_NO)
 WHERE SOUP_NO = 38 
   AND SOUP_MEMBER_STATUS = 'BELONG'
 GROUP BY SOUP_MEMBER_MAX
